### ISSUE TITLE
SearchForm extends BaseUsrForm not CFormModel

### ISSUE THREAD

**Issue by rossaddison** [nineinchnick/yii-usr#58]
Bug.  I have tried your code recently (SearchForm.php) and had to change SearchForm extends CFormModel to SearchForm extends BaseUsrForm otherwise Line 343  of UsrModule raises an error.

$form->webUser = Yii::app()->user;

Error message:    SearchForm.webUser is undefined. 

$webUsr is a public variable under the BaseUsrForm not under the CFormModel.  

The code is working fine otherwise. Thanks for all your efforts.  Will tackle email verification a little bit later.

**Comment by nineinchnick** [comment]
Sorry about that, totaly my fault for not checking it.
